# Generated by Django 6.0.7 on 2026-07-25 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('text', models.TextField(verbose_name='Text')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News-Beitrag',
                'verbose_name_plural': 'News-Beiträge',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notfallkontakt_name', models.CharField(blank=True, max_length=200, verbose_name='Notfallkontakt Name')),
                ('notfallkontakt_telefon', models.CharField(blank=True, max_length=50, verbose_name='Notfallkontakt Telefon')),
                ('notfallkontakt_beziehung', models.CharField(blank=True, help_text='z.B. Mutter, Vater, Partner:in', max_length=100, verbose_name='Beziehung zum Notfallkontakt')),
                ('schuhgroesse', models.CharField(blank=True, max_length=10, verbose_name='Schuhgröße')),
                ('allergien', models.TextField(blank=True, verbose_name='Allergien')),
                ('medikamente', models.TextField(blank=True, verbose_name='Medikamente')),
                ('sonstige_hinweise', models.TextField(blank=True, help_text='z.B. Vorerkrankungen, Besonderheiten', verbose_name='Sonstige Hinweise')),
                ('stammdaten_bestaetigt_am', models.DateTimeField(blank=True, null=True, verbose_name='Stammdaten zuletzt bestätigt am')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('art', models.CharField(choices=[('training', 'Training'), ('veranstaltung', 'Veranstaltung')], default='training', max_length=20, verbose_name='Art')),
                ('beginn', models.DateTimeField(verbose_name='Beginn')),
                ('ort', models.CharField(blank=True, max_length=200, verbose_name='Ort')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_termine', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Termine',
                'ordering': ['beginn'],
            },
        ),
        migrations.CreateModel(
            name='Zusage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('zugesagt', 'Zugesagt'), ('abgesagt', 'Abgesagt'), ('offen', 'Noch offen')], default='offen', max_length=20, verbose_name='Status')),
                ('kommentar', models.CharField(blank=True, max_length=300, verbose_name='Kommentar')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('mitglied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zusagen', to=settings.AUTH_USER_MODEL)),
                ('termin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zusagen', to='mitglieder.termin')),
            ],
            options={
                'verbose_name': 'Zu-/Absage',
                'verbose_name_plural': 'Zu-/Absagen',
                'unique_together': {('mitglied', 'termin')},
            },
        ),
    ]
