# Generated by Django 6.0.7 on 2026-07-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0002_taenzerin_kinder_umbau'),
    ]

    operations = [
        migrations.AddField(
            model_name='taenzerin',
            name='geburtsjahr',
            field=models.PositiveIntegerField(blank=True, help_text='Bestimmt die Trainingsgruppe (Jugend/Junioren).', null=True, verbose_name='Geburtsjahr'),
        ),
        migrations.AddField(
            model_name='termin',
            name='ende',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ende'),
        ),
        migrations.AddField(
            model_name='termin',
            name='gruppe',
            field=models.CharField(choices=[('beide', 'Beide Gruppen'), ('jugend', 'Jugend'), ('junioren', 'Junioren')], default='beide', max_length=20, verbose_name='Gruppe'),
        ),
    ]
