# Generated by Django 6.0.7 on 2026-07-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0003_taenzerin_geburtsjahr_termin_ende_termin_gruppe'),
    ]

    operations = [
        migrations.AddField(
            model_name='taenzerin',
            name='kleidergroesse',
            field=models.CharField(blank=True, max_length=10, verbose_name='Kleidergröße'),
        ),
    ]
