# Generated by Django 6.0.7 on 2026-07-27 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0005_betreuer_gruppe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anmeldepunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(help_text="z.B. 'Kuchen mitbringen', 'Aufbauhelfer', 'Fahrdienst'", max_length=200, verbose_name='Titel')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('max_anzahl', models.PositiveIntegerField(blank=True, help_text='Leer lassen für unbegrenzt viele Anmeldungen', null=True, verbose_name='Benötigte Anzahl')),
                ('termin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anmeldepunkte', to='mitglieder.termin')),
            ],
            options={
                'verbose_name': 'Helfer-/Mitbringpunkt',
                'verbose_name_plural': 'Helfer-/Mitbringpunkte',
            },
        ),
        migrations.CreateModel(
            name='Anmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kommentar', models.CharField(blank=True, help_text='z.B. was du mitbringst', max_length=300, verbose_name='Kommentar')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('anmeldepunkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anmeldungen', to='mitglieder.anmeldepunkt')),
                ('eltern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helfer_anmeldungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anmeldung',
                'verbose_name_plural': 'Anmeldungen',
                'unique_together': {('anmeldepunkt', 'eltern')},
            },
        ),
    ]
