# Generated by Django 6.0.7 on 2026-07-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0007_betreuer_helferliste_rechte'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingTermin',
            fields=[
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mitglieder.termin',),
        ),
        migrations.CreateModel(
            name='VeranstaltungTermin',
            fields=[
            ],
            options={
                'verbose_name': 'Veranstaltung',
                'verbose_name_plural': 'Veranstaltungen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mitglieder.termin',),
        ),
    ]
