# Generated by Django 6.0.7 on 2026-07-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0008_trainingtermin_veranstaltungtermin'),
    ]

    operations = [
        migrations.AddField(
            model_name='anmeldepunkt',
            name='mit_kommentar',
            field=models.BooleanField(default=True, help_text='Aktiviert: Eltern können angeben, was sie mitbringen. Deaktiviert: reine Helferliste, einfach nur eintragen.', verbose_name='Mit Kommentar (z.B. für Mitbringen)'),
        ),
    ]
