# Generated by Django 6.0.7 on 2026-07-27 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0009_anmeldepunkt_mit_kommentar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('erledigt', models.BooleanField(default=False, verbose_name='Erledigt')),
                ('erledigt_am', models.DateTimeField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aufgaben', to=settings.AUTH_USER_MODEL)),
                ('termin', models.ForeignKey(blank=True, help_text='Optional: zu welcher Veranstaltung gehört die Aufgabe? Leer lassen für allgemeine Planung.', limit_choices_to={'art': 'veranstaltung'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aufgaben', to='mitglieder.termin', verbose_name='Veranstaltung')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben (To-Do)',
                'ordering': ['erledigt', 'termin__beginn', '-erstellt_am'],
            },
        ),
    ]
