# Generated by Django 6.0.7 on 2026-07-27 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0011_betreuer_aufgaben_rechte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe',
            name='erstellt_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aufgaben', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='termin',
            name='erstellt_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_termine', to=settings.AUTH_USER_MODEL),
        ),
    ]
