# Generated by Django 6.0.7 on 2026-07-27 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0012_alter_aufgabe_erstellt_von_alter_termin_erstellt_von'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='zusage',
            name='anwesend',
            field=models.BooleanField(blank=True, help_text='Von Admin/Betreuer nach dem Termin bestätigt. Leer = noch nicht erfasst.', null=True, verbose_name='Anwesend'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betreff', models.CharField(blank=True, max_length=200, verbose_name='Betreff')),
                ('nachricht', models.TextField(verbose_name='Nachricht')),
                ('gelesen', models.BooleanField(default=False, verbose_name='Gelesen')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('absender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback / Nachrichten',
                'ordering': ['gelesen', '-erstellt_am'],
            },
        ),
    ]
