# Generated by Django 6.0.7 on 2026-07-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0014_betreuer_feedback_rechte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferienzeitraum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="z.B. 'Sommerferien 2026'", max_length=100, verbose_name='Name')),
                ('start_datum', models.DateField(verbose_name='Von')),
                ('end_datum', models.DateField(verbose_name='Bis (einschließlich)')),
            ],
            options={
                'verbose_name': 'Ferienzeitraum',
                'verbose_name_plural': 'Ferienzeiträume (Bayern)',
                'ordering': ['start_datum'],
            },
        ),
    ]
