# Generated by Django 6.0.7 on 2026-07-28 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0017_betreuer_veranstaltung_news_helferliste_rechte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taenzerin',
            name='mitverwaltet_von',
            field=models.ManyToManyField(blank=True, help_text='Weitere Benutzer (z.B. Partner:in), die dieses Kind ebenfalls sehen und verwalten dürfen.', related_name='mitverwaltete_kinder', to=settings.AUTH_USER_MODEL, verbose_name='Mitverwaltet von'),
        ),
    ]
