# Generated by Django 6.0.7 on 2026-07-28 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0018_taenzerin_mitverwaltet_von'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='zugewiesen_an',
            field=models.ForeignKey(blank=True, help_text='Optional: welches Orga-/Admin-Teammitglied kümmert sich darum?', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zugewiesene_aufgaben', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an'),
        ),
    ]
