# Generated by Django 6.0.7 on 2026-07-28 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0019_aufgabe_zugewiesen_an'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anmeldepunkt',
            name='termin',
            field=models.ForeignKey(blank=True, help_text="Optional: zu welcher Veranstaltung gehört das? Leer lassen für eine allgemeine Aufgabe (z.B. 'Leibchen waschen'), zu der sich Mitglieder unabhängig von einem Termin eintragen können.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anmeldepunkte', to='mitglieder.termin'),
        ),
    ]
