# Generated by Django 6.0.7 on 2026-07-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0020_alter_anmeldepunkt_termin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='nur_team',
            field=models.BooleanField(default=False, help_text='Aktiviert: nur Orga-/Admin-Team sieht diese Aufgabe im Mitgliederbereich und kann sie übernehmen. Deaktiviert: auch Eltern können sich dafür eintragen.', verbose_name='Nur Orga-/Admin-Team'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='zugewiesen_an',
            field=models.ForeignKey(blank=True, help_text='Optional: wer kümmert sich darum? (Wird auch automatisch gesetzt, wenn sich jemand im Mitgliederbereich selbst einträgt.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zugewiesene_aufgaben', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an'),
        ),
    ]
