# Generated by Django 6.0.7 on 2026-07-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0021_aufgabe_nur_team_alter_aufgabe_zugewiesen_an'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe',
            name='nur_team',
            field=models.BooleanField(default=True, help_text='Aktiviert: nur Orga-/Admin-Team sieht diese Aufgabe im Mitgliederbereich und kann sie übernehmen. Deaktiviert: auch Eltern können sich dafür eintragen.', verbose_name='Nur Orga-/Admin-Team'),
        ),
    ]
