# Generated by Django 6.0.7 on 2026-07-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0023_bestehende_aufgaben_nur_team'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anmeldung',
            unique_together=set(),
        ),
    ]
