# Generated by Django 6.0.7 on 2026-07-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0024_alter_anmeldung_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='taenzerinnen_erforderlich',
            field=models.BooleanField(default=True, help_text="Deaktivieren bei Veranstaltungen ohne Auftritt der Tänzerinnen, z.B. 'Ladies Night'.", verbose_name='Tänzerinnen müssen anwesend sein (Auftritt)'),
        ),
    ]
