# Generated by Django 6.0.7 on 2026-07-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0025_termin_taenzerinnen_erforderlich'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='faellig_am',
            field=models.DateField(blank=True, help_text="Optional: bis wann soll die Aufgabe erledigt sein? (z.B. 'Leibchen waschen' bis zum nächsten Training).", null=True, verbose_name='Fällig am'),
        ),
    ]
