# Generated by Django 6.0.7 on 2026-07-29 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0026_aufgabe_faellig_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='wichtiges_training',
            field=models.ForeignKey(blank=True, help_text='Optional: z.B. bei einer Veranstaltung auf ein Training verweisen, zu dem Anwesenheit wichtig ist (etwa eine Generalprobe).', limit_choices_to={'art': 'training'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wichtig_fuer_veranstaltungen', to='mitglieder.termin', verbose_name='Wichtiges Training (Verweis)'),
        ),
    ]
