# Generated by Django 6.0.7 on 2026-07-29 22:16

from django.db import migrations, models


def alte_werte_uebernehmen(apps, schema_editor):
    Termin = apps.get_model("mitglieder", "Termin")
    for termin in Termin.objects.exclude(wichtiges_training__isnull=True):
        termin.wichtige_trainings.add(termin.wichtiges_training_id)


def keine_umkehrung_moeglich(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0027_termin_wichtiges_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='wichtige_trainings',
            field=models.ManyToManyField(blank=True, help_text='Optional: z.B. bei einer Veranstaltung auf ein oder mehrere Trainings verweisen, zu denen Anwesenheit wichtig ist (etwa Generalproben).', limit_choices_to={'art': 'training'}, related_name='wichtig_fuer_veranstaltungen', to='mitglieder.termin', verbose_name='Wichtige Trainings (Verweis)'),
        ),
        migrations.RunPython(alte_werte_uebernehmen, keine_umkehrung_moeglich),
        migrations.RemoveField(
            model_name='termin',
            name='wichtiges_training',
        ),
    ]
