# Generated by Django 6.0.7 on 2026-07-29 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0028_remove_termin_wichtiges_training_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeriebild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild', models.ImageField(upload_to='galerie/', verbose_name='Bild')),
                ('beschreibung', models.CharField(blank=True, max_length=200, verbose_name='Beschreibung')),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
                ('hochgeladen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hochgeladene_bilder', to=settings.AUTH_USER_MODEL)),
                ('termin', models.ForeignKey(blank=True, help_text='Optional: zu welcher Veranstaltung gehört das Bild? Leer lassen für die allgemeine Galerie.', limit_choices_to={'art': 'veranstaltung'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeriebilder', to='mitglieder.termin', verbose_name='Veranstaltung')),
            ],
            options={
                'verbose_name': 'Galeriebild',
                'verbose_name_plural': 'Galeriebilder',
                'ordering': ['-hochgeladen_am'],
            },
        ),
    ]
