# Generated by Django 6.0.7 on 2026-07-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0029_galeriebild'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Bild'),
        ),
    ]
