# Generated by Django 6.0.7 on 2026-07-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0030_newspost_bild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='text',
            field=models.TextField(blank=True, help_text='Optional, wenn stattdessen nur ein Bild gezeigt werden soll.', verbose_name='Text'),
        ),
    ]
