# Generated by Django 6.0.7 on 2026-07-30 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0031_alter_newspost_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taenzerin',
            name='nutzer',
            field=models.OneToOneField(blank=True, help_text='Falls dieser Eintrag zu einem eigenen Login-Konto gehört (z.B. eine Tänzerin mit eigenem Zugang statt rein von einem Elternteil verwaltet zu werden).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taenzerin_konto', to=settings.AUTH_USER_MODEL, verbose_name='Gehört zu Benutzerkonto'),
        ),
    ]
