# Generated by Django 6.0.7 on 2026-07-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0033_aufgabe_sichtbar_fuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='interne_notiz',
            field=models.TextField(blank=True, help_text='Nicht öffentlich – nur für Orga-/Admin-Team sichtbar, z.B. im Mitgliederbereich.', verbose_name='Interne Notiz'),
        ),
    ]
