# Generated by Django 6.0.7 on 2026-07-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0034_termin_interne_notiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='taenzerin',
            name='einverstaendnis_bildaufnahmen',
            field=models.BooleanField(blank=True, default=None, help_text='Muss separat bestätigt werden, ist nicht Teil der allgemeinen Stammdaten-Bestätigung. Leer = noch nicht entschieden.', null=True, verbose_name='Einverständnis Bild-/Videoaufnahmen (Social Media, Homepage, Presse)'),
        ),
        migrations.AddField(
            model_name='taenzerin',
            name='einverstaendnis_bildaufnahmen_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Einverständnis zuletzt bestätigt am'),
        ),
    ]
