# Generated by Django 6.0.7 on 2026-07-31 21:53

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def geburtsjahr_zu_geburtsdatum(apps, schema_editor):
    Taenzerin = apps.get_model('mitglieder', 'Taenzerin')
    for kind in Taenzerin.objects.exclude(geburtsjahr=None):
        kind.geburtsdatum = datetime.date(kind.geburtsjahr, 1, 1)
        kind.save(update_fields=['geburtsdatum'])


def geburtsdatum_zu_geburtsjahr(apps, schema_editor):
    Taenzerin = apps.get_model('mitglieder', 'Taenzerin')
    for kind in Taenzerin.objects.exclude(geburtsdatum=None):
        kind.geburtsjahr = kind.geburtsdatum.year
        kind.save(update_fields=['geburtsjahr'])


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0035_taenzerin_einverstaendnis_bildaufnahmen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taenzerin',
            name='abholberechtigte',
            field=models.TextField(blank=True, help_text='Namen der Personen, die die Tänzerin/den Tänzer abholen dürfen (falls nicht selbstständig nach Hause darf).', verbose_name='Abholberechtigte'),
        ),
        migrations.AddField(
            model_name='taenzerin',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='taenzerin',
            name='alleine_nach_hause',
            field=models.BooleanField(blank=True, default=None, help_text='Leer = noch nicht angegeben.', null=True, verbose_name='Darf nach dem Training selbstständig nach Hause'),
        ),
        migrations.AddField(
            model_name='taenzerin',
            name='geburtsdatum',
            field=models.DateField(blank=True, help_text='Bestimmt die Trainingsgruppe (Jugend/Junioren).', null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AddField(
            model_name='taenzerin',
            name='mobil',
            field=models.CharField(blank=True, help_text='Eigene Mobilnummer der Tänzerin/des Tänzers, falls vorhanden.', max_length=50, verbose_name='Mobil'),
        ),
        migrations.AddField(
            model_name='taenzerin',
            name='plz_ort',
            field=models.CharField(blank=True, max_length=100, verbose_name='PLZ / Ort'),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hilfe_fahrdienste', models.BooleanField(default=False, verbose_name='Fahrdienste')),
                ('hilfe_veranstaltungen', models.BooleanField(default=False, verbose_name='Veranstaltungen')),
                ('hilfe_kuchen_essensspenden', models.BooleanField(default=False, verbose_name='Kuchen / Essensspenden')),
                ('hilfe_dekoration_basteln', models.BooleanField(default=False, verbose_name='Dekoration / Basteln')),
                ('hilfe_naehen_aenderungen', models.BooleanField(default=False, verbose_name='Nähen / Änderungen an Kostümen')),
                ('hilfe_fotos_social_media', models.BooleanField(default=False, verbose_name='Fotos / Social Media')),
                ('hilfe_organisation', models.BooleanField(default=False, verbose_name='Organisation')),
                ('hilfe_sponsoring_kontakte', models.BooleanField(default=False, verbose_name='Sponsoring / Kontakte')),
                ('hilfe_sonstiges', models.CharField(blank=True, max_length=200, verbose_name='Sonstiges')),
                ('einverstanden_datennutzung', models.BooleanField(default=False, verbose_name='Einverstanden, dass meine Daten für vereinsinterne Zwecke genutzt werden')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.RunPython(geburtsjahr_zu_geburtsdatum, geburtsdatum_zu_geburtsjahr),
        migrations.RemoveField(
            model_name='taenzerin',
            name='geburtsjahr',
        ),
    ]
