# Generated by Django 6.0.7 on 2026-07-31 22:15

from django.db import migrations, models


def unbestaetigte_false_werte_zuruecksetzen(apps, schema_editor):
    """Bisher defaultete das Feld unbestaetigt auf False (angehaktes Kaestchen war die
    einzige Form von 'ja'). Ohne eigenen Zeitstempel wurde nie aktiv bestaetigt/abgelehnt,
    darum auf 'noch nicht entschieden' (None) zuruecksetzen."""
    Profil = apps.get_model('mitglieder', 'Profil')
    Profil.objects.filter(
        einverstanden_datennutzung=False, einverstanden_datennutzung_am__isnull=True,
    ).update(einverstanden_datennutzung=None)


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0036_remove_taenzerin_geburtsjahr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='einverstanden_datennutzung_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Einverständnis zuletzt bestätigt am'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='einverstanden_datennutzung',
            field=models.BooleanField(blank=True, default=None, help_text='Muss separat bestätigt werden. Leer = noch nicht entschieden.', null=True, verbose_name='Einverstanden, dass meine Daten für vereinsinterne Zwecke genutzt werden'),
        ),
        migrations.RunPython(unbestaetigte_false_werte_zuruecksetzen, migrations.RunPython.noop),
    ]
