# Generated by Django 6.0.7 on 2026-07-31 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0037_profil_einverstanden_datennutzung_am_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AufgabeErledigung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erledigt_am', models.DateTimeField(auto_now_add=True)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erledigungen', to='mitglieder.aufgabe')),
                ('taenzerin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aufgaben_erledigungen', to='mitglieder.taenzerin')),
            ],
            options={
                'verbose_name': 'Aufgaben-Erledigung',
                'verbose_name_plural': 'Aufgaben-Erledigungen',
                'unique_together': {('aufgabe', 'taenzerin')},
            },
        ),
    ]
