# Generated by Django 6.0.7 on 2026-08-01 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0038_aufgabeerledigung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galerieordner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Galerie-Ordner',
                'verbose_name_plural': 'Galerie-Ordner',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.AddField(
            model_name='galeriebild',
            name='ordner',
            field=models.ForeignKey(blank=True, help_text='Optional: alternativ zu einer Veranstaltung - Ordner in der allgemeinen Galerie.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilder', to='mitglieder.galerieordner', verbose_name='Ordner'),
        ),
    ]
