# Generated by Django 6.0.7 on 2026-08-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0039_galerieordner_galeriebild_ordner'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriebild',
            name='titelbild',
            field=models.BooleanField(default=False, help_text='Wird in der Galerie-Übersicht zuerst und größer angezeigt (nur eines pro Ordner/Veranstaltung).', verbose_name='Titelbild'),
        ),
    ]
