# Generated by Django 6.0.7 on 2026-08-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0040_galeriebild_titelbild'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='uhrzeit_unbekannt',
            field=models.BooleanField(default=False, help_text='Datum ist bekannt, aber die genaue Uhrzeit noch nicht - wird den Mitgliedern als "Uhrzeit folgt noch" angezeigt (die Uhrzeit von Beginn/Ende wird dann ignoriert).', verbose_name='Uhrzeit steht noch nicht fest'),
        ),
    ]
