# Generated by Django 6.0.7 on 2026-08-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0041_termin_uhrzeit_unbekannt'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='beschreibung_bild',
            field=models.ImageField(blank=True, help_text='Optional: wird zusammen mit der Beschreibung angezeigt, z.B. ein Flyer.', null=True, upload_to='termine/', verbose_name='Bild zur Beschreibung'),
        ),
    ]
