# Generated by Django 6.0.7 on 2026-08-01 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0042_termin_beschreibung_bild'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerieordner',
            name='veranstaltung',
            field=models.ForeignKey(blank=True, help_text='Optional: den kompletten Ordner (inkl. aller Bilder) einer Veranstaltung zuordnen - die Bilder erscheinen dann in der Galerie unter dieser Veranstaltung statt als eigener Ordner.', limit_choices_to={'art': 'veranstaltung'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galerie_ordner', to='mitglieder.termin', verbose_name='Veranstaltung'),
        ),
    ]
