# Generated by Django 6.0.7 on 2026-08-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0043_galerieordner_veranstaltung'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='admin_menu_verstecken',
            field=models.BooleanField(default=False, help_text='Falls aktiv: Trotz Admin-/Staff-Rechten wird im Mitgliederbereich kein Admin-Link angezeigt - man sieht dem Konto in der normalen Ansicht also nicht an, dass es Admin-Rechte hat.', verbose_name='Admin-Hinweis im Mitgliederbereich verstecken'),
        ),
    ]
