# Generated by Django 6.0.7 on 2026-08-03 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0043_galerieordner_veranstaltung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nachricht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betreff', models.CharField(blank=True, max_length=200, verbose_name='Betreff')),
                ('nachricht', models.TextField(verbose_name='Nachricht')),
                ('gelesen', models.BooleanField(default=False, verbose_name='Gelesen')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('absender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gesendete_nachrichten', to=settings.AUTH_USER_MODEL)),
                ('empfaenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erhaltene_nachrichten', to=settings.AUTH_USER_MODEL, verbose_name='An')),
            ],
            options={
                'verbose_name': 'Nachricht an Mitglied',
                'verbose_name_plural': 'Nachrichten an Mitglieder',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
