# Generated by Django 6.0.7 on 2026-08-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0044_nachricht'),
    ]

    operations = [
        migrations.CreateModel(
            name='Einstellungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugend_jahrgang_ab', models.PositiveIntegerField(default=2016, help_text="Tänzerinnen mit Geburtsjahr ab dieser Zahl gehören zur Gruppe 'Jugend', ältere zu 'Junioren'. Am besten jährlich anpassen, damit die Altersgruppen aktuell bleiben.", verbose_name='Jugend ab Jahrgang')),
            ],
            options={
                'verbose_name': 'Einstellungen',
                'verbose_name_plural': 'Einstellungen',
            },
        ),
    ]
