# Generated by Django 6.0.7 on 2026-08-04 20:19

from django.db import migrations, models


def gruppen_seeden_und_migrieren(apps, schema_editor):
    Gruppe = apps.get_model('mitglieder', 'Gruppe')
    Termin = apps.get_model('mitglieder', 'Termin')
    Einstellungen = apps.get_model('mitglieder', 'Einstellungen')

    jugend_ab = 2016
    einstellung = Einstellungen.objects.first()
    if einstellung:
        jugend_ab = einstellung.jugend_jahrgang_ab

    jugend, _ = Gruppe.objects.get_or_create(name='Jugend', defaults={'jahrgang_ab': jugend_ab})
    junioren, _ = Gruppe.objects.get_or_create(name='Junioren', defaults={'jahrgang_ab': 1900})

    for termin in Termin.objects.all():
        if termin.gruppe == 'jugend':
            termin.gruppen.add(jugend)
        elif termin.gruppe == 'junioren':
            termin.gruppen.add(junioren)
        # 'beide' -> gruppen bleibt leer (gilt jetzt fuer alle Gruppen, auch kuenftig neu angelegte)


def gruppen_seeden_und_migrieren_rueckgaengig(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0045_einstellungen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Jugend, Junioren, Damen', max_length=50, unique=True, verbose_name='Name')),
                ('jahrgang_ab', models.IntegerField(help_text='Tänzerinnen mit diesem Geburtsjahr oder jünger gehören zu dieser Gruppe - es sei denn, eine andere Gruppe hat eine noch höhere Jahrgangsgrenze und passt damit besser. Die Gruppe mit der niedrigsten Zahl fängt automatisch auch alle älteren Jahrgänge auf.', unique=True, verbose_name='Jahrgang ab')),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppen',
                'ordering': ['-jahrgang_ab'],
            },
        ),
        migrations.AddField(
            model_name='termin',
            name='gruppen',
            field=models.ManyToManyField(blank=True, help_text='Für welche Gruppen gilt dieser Termin? Leer lassen = gilt für alle Gruppen.', to='mitglieder.gruppe', verbose_name='Gruppen'),
        ),
        migrations.RunPython(gruppen_seeden_und_migrieren, gruppen_seeden_und_migrieren_rueckgaengig),
        migrations.RemoveField(
            model_name='termin',
            name='gruppe',
        ),
        migrations.DeleteModel(
            name='Einstellungen',
        ),
        migrations.AlterField(
            model_name='taenzerin',
            name='geburtsdatum',
            field=models.DateField(blank=True, help_text='Bestimmt die Trainingsgruppe (siehe Verwaltung unter Gruppen).', null=True, verbose_name='Geburtsdatum'),
        ),
    ]
