# Generated by Django 6.0.7 on 2026-08-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0047_verwaiste_spalte_entfernen'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='anzeigen_bis',
            field=models.DateField(blank=True, help_text='Optional: ab dem Folgetag wird der Beitrag nicht mehr angezeigt. Leer = zeitlich unbegrenzt.', null=True, verbose_name='Anzeigen bis'),
        ),
    ]
