# Generated by Django 6.0.7 on 2026-08-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0048_newspost_anzeigen_bis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anmeldepunkt',
            options={'verbose_name': 'Helfer-/Mitbringliste', 'verbose_name_plural': 'Helfer-/Mitbringlisten'},
        ),
        migrations.AlterModelOptions(
            name='gruppe',
            options={'ordering': ['-jahrgang_ab'], 'verbose_name': 'Trainingsgruppe', 'verbose_name_plural': 'Trainingsgruppen'},
        ),
    ]
