# Generated by Django 6.0.7 on 2026-09-16 14:39

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0049_alter_anmeldepunkt_options_alter_gruppe_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AufgabeDatei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datei', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='aufgaben/', verbose_name='Datei')),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dateien', to='mitglieder.aufgabe')),
            ],
            options={
                'verbose_name': 'Datei',
                'verbose_name_plural': 'Dateien',
            },
        ),
    ]
