# Generated by Django 6.0.7 on 2026-09-16 14:43

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0050_aufgabedatei'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainingsmaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('pdf', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='trainingsmaterial/pdf/', verbose_name='PDF (Trainingsplan)')),
                ('video', models.FileField(blank=True, help_text='Grössere Videos können beim Hochladen etwas dauern.', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='trainingsmaterial/video/', verbose_name='Video')),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
                ('hochgeladen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hochgeladene_trainingsmaterialien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainingsplan / Video',
                'verbose_name_plural': 'Trainingspläne / Videos',
                'ordering': ['-hochgeladen_am'],
            },
        ),
    ]
