# Generated by Django 6.0.7 on 2026-10-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0052_anmeldung_oeffentlich_termin_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='ist_entwurf',
            field=models.BooleanField(default=False, help_text='Aktiviert: Der Termin ist im Mitgliederbereich (Übersicht, Kalender, Erinnerungs-Mails, öffentlicher Teilen-Link) unsichtbar - praktisch, um erst alles vorzubereiten, bevor er veröffentlicht wird. Hier im Admin-Bereich bleibt er sichtbar.', verbose_name='Entwurf (für Mitglieder noch nicht sichtbar)'),
        ),
        migrations.AlterField(
            model_name='anmeldung',
            name='name_ohne_konto',
            field=models.CharField(blank=True, help_text='Nur ausgefüllt bei einer Anmeldung über den öffentlichen WhatsApp-Link ohne App-Konto.', max_length=150, verbose_name='Name (ohne Konto)'),
        ),
        migrations.AlterField(
            model_name='termin',
            name='gruppen',
            field=models.ManyToManyField(blank=True, help_text="Wenn ausgewählt: Auftritt für diese Gruppe(n). Leer lassen = kein Auftritt (z.B. 'Ladies Night').", to='mitglieder.gruppe', verbose_name='Gruppen'),
        ),
        migrations.AlterField(
            model_name='termin',
            name='taenzerinnen_erforderlich',
            field=models.BooleanField(default=True, help_text="Ergibt sich automatisch aus der Gruppenauswahl oben: keine Gruppe ausgewählt = kein Auftritt nötig (z.B. 'Ladies Night'), mindestens eine Gruppe = Auftritt.", verbose_name='Tänzerinnen müssen anwesend sein (Auftritt)'),
        ),
    ]
