# Generated by Django 6.0.7 on 2026-10-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0053_termin_ist_entwurf_alter_anmeldung_name_ohne_konto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anmeldepunkt',
            name='benoetigt_am',
            field=models.DateTimeField(blank=True, help_text='Optional: bei mehrtägigen Terminen, für welchen Tag/welche Uhrzeit genau das gebraucht bzw. abgegeben werden soll (z.B. Frühstück am 2. Tag, 8 Uhr).', null=True, verbose_name='Benötigt am'),
        ),
    ]
