# Generated by Django 6.0.7 on 2026-10-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0054_anmeldepunkt_benoetigt_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='anmeldepunkt',
            name='ist_entwurf',
            field=models.BooleanField(default=False, help_text='Aktiviert: Eltern sehen diesen Punkt noch nicht, auch wenn die Veranstaltung selbst schon sichtbar ist - nützlich, wenn erst später feststeht, welche Helfer-/Mitbringlisten es braucht.', verbose_name='Entwurf (noch nicht für Eltern sichtbar)'),
        ),
    ]
