# Generated by Django 6.0.7 on 2026-10-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0055_anmeldepunkt_ist_entwurf'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='kategorie',
            field=models.CharField(choices=[('helferliste', 'Helferliste'), ('bringliste', 'Bringliste'), ('sonstiges', 'Sonstiges')], default='sonstiges', help_text='Dient zur Gruppierung auf der ToDo-Seite, z.B. bei vielen Schichten/Aufgaben zu einer Veranstaltung.', max_length=20, verbose_name='Kategorie'),
        ),
    ]
