# Generated by Django 6.0.7 on 2026-07-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(help_text="z.B. 'Anmeldung Sommerlager'", max_length=200, verbose_name='Titel')),
                ('datei', models.FileField(upload_to='formulare/', verbose_name='Datei')),
                ('reihenfolge', models.PositiveIntegerField(default=0, help_text='Kleinere Zahl wird zuerst angezeigt.', verbose_name='Reihenfolge')),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formular',
                'verbose_name_plural': 'Formulare',
                'ordering': ['reihenfolge', 'titel'],
            },
        ),
    ]
