# Generated by Django 6.0.7 on 2026-08-01 10:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formular',
            name='datei',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='formulare/', verbose_name='Datei'),
        ),
    ]
