# Generated by Django 6.0.7 on 2026-08-01 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0002_alter_formular_datei'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formular',
            options={'ordering': ['titel'], 'verbose_name': 'Formular', 'verbose_name_plural': 'Formulare'},
        ),
        migrations.RemoveField(
            model_name='formular',
            name='reihenfolge',
        ),
    ]
