"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Lokal wird der Default-Key genutzt, auf dem Server per Umgebungsvariable überschreiben.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-6jj$ptl*rqie!5ps=rz!^_bmdr@fv62r$skloswcchj&(k0a^f',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1'
).split(',')

CSRF_TRUSTED_ORIGINS = [
    origin for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if origin
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'mitglieder',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS hat Vorrang vor APP_DIRS: noetig, damit unsere eigene
        # admin/base_site.html Django-contrib.admin's gleichnamige Datei ueberschreibt.
        'DIRS': [BASE_DIR / 'mitglieder' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mitglieder.context_processors.kontakte_abteilungen',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# Gilt nur beim Setzen eines NEUEN Passworts (Registrierung, Passwort-Aenderung/-Reset) -
# bereits registrierte Mitglieder muessen ihr bestehendes Passwort deswegen nicht aendern.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'mitglieder.password_validators.KomplexitaetValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Von Nutzerinnen hochgeladene Dateien (Galeriebilder). Werden bei gesetzten
# Zugangsdaten automatisch zu Cloudinary hochgeladen (kostenloser externer
# Bilder-Hosting-Dienst), damit sie nicht das PythonAnywhere-Speicherlimit
# belasten. Ohne gesetzte Zugangsdaten (z.B. lokal) landen sie stattdessen
# ganz normal im lokalen 'media'-Ordner.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('DJANGO_CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY': os.environ.get('DJANGO_CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.environ.get('DJANGO_CLOUDINARY_API_SECRET', ''),
}
# Django 4.2+ konfiguriert den Datei-Speicher über STORAGES statt der alten
# (in Django 6 entfernten) Einstellung DEFAULT_FILE_STORAGE.
STORAGES = {
    'default': {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage'
        if CLOUDINARY_STORAGE['CLOUD_NAME']
        else 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# PythonAnywhere-Gratis-Plan: ausgehende Verbindungen funktionieren nur ueber den
# vom System gesetzten https_proxy/http_proxy - direkte Verbindungen (auch zu
# Domains auf der Allowlist) werden sonst mit "Connection refused" abgelehnt.
# Das Cloudinary-SDK nutzt urllib3 direkt und liest diese Proxy-Umgebungsvariablen
# anders als z.B. 'requests' NICHT automatisch, darum hier explizit setzen.
if CLOUDINARY_STORAGE['CLOUD_NAME']:
    _cloudinary_proxy = os.environ.get('https_proxy') or os.environ.get('HTTPS_PROXY')
    if _cloudinary_proxy:
        import cloudinary
        cloudinary.config(api_proxy=_cloudinary_proxy)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login/Logout
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# E-Mail: standardmäßig landen Mails nur in der Konsole/im Server-Log.
# Ausgehende SMTP-Verbindungen sind auf dem kostenlosen PythonAnywhere-Plan blockiert,
# darum für den echten Versand 'mitglieder.email_backend.BrevoAPIBackend' nutzen
# (spricht die Brevo-API per HTTPS an, das ist auf dem Gratis-Plan erlaubt).
EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('DJANGO_EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('DJANGO_EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('DJANGO_EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM_EMAIL', 'Garde Tanz <noreply@garde-tanz.example>')
BREVO_API_KEY = os.environ.get('DJANGO_BREVO_API_KEY', '')

# Code, den Eltern bei der Selbstregistrierung eingeben müssen (z.B. zusammen mit
# dem Registrierungslink in der WhatsApp-Gruppe teilen). Auf dem Server per
# Umgebungsvariable überschreiben, um den Code jederzeit zu ändern.
EINLADUNGSCODE = os.environ.get('DJANGO_EINLADUNGSCODE', 'gardetanz')

# Der Pfad-Teil der Registrierungs-URL (z.B. 'registrieren' -> /registrieren/).
# Auf dem Server per Umgebungsvariable überschreiben, um den Link umzubenennen.
REGISTRIERUNGS_SLUG = os.environ.get('DJANGO_REGISTRIERUNGS_SLUG', 'registrieren')

# Feste Zusatz-Adresse für System-Benachrichtigungen (z.B. neue Registrierung).
# Wird IMMER zusätzlich zu den E-Mail-Adressen aller Admin-/Betreuer-Konten benutzt,
# damit eine Benachrichtigung nicht ausbleibt, nur weil bei einem Konto keine
# E-Mail-Adresse hinterlegt ist. Optional, auf dem Server per Umgebungsvariable setzen.
ADMIN_BENACHRICHTIGUNGS_EMAIL = os.environ.get('DJANGO_ADMIN_BENACHRICHTIGUNGS_EMAIL', '')
